export const MILESTONES = [
  { index: 0, name: "Land Preparation", releaseBps: 1500, trigger: "Farmer submits GPS + photo proof" },
  { index: 1, name: "Planting", releaseBps: 2000, trigger: "AI verifies seeds/rows in soil" },
  { index: 2, name: "Seedling Phase", releaseBps: 2000, trigger: "AI confirms seedling emergence" },
  { index: 3, name: "Vegetative Growth", releaseBps: 1500, trigger: "AI detects canopy growth" },
  { index: 4, name: "Tasseling / Pre-Harvest", releaseBps: 1500, trigger: "AI confirms tasseling" },
  { index: 5, name: "Harvest Complete", releaseBps: 1500, trigger: "Farmer voice + photo confirm" },
] as const;

export const CAMPAIGN_STATUSES = {
  Active: "Active",
  Funded: "Funded",
  Harvested: "Harvested",
  Failed: "Failed",
} as const;

export const RISK_TIERS = {
  Low: "Low",
  Medium: "Medium",
  High: "High",
} as const;

export const LOADING_MESSAGES = [
  "Checking your soil data...",
  "Asking the blockchain...",
  "Verifying your seedlings...",
  "Consulting the weather spirits...",
  "Measuring the maize height...",
  "Counting the rows...",
  "Checking rainfall patterns...",
  "Preparing your harvest report...",
];

export const MOCK_CAMPAIGNS = [
  {
    id: "farm-1",
    farmerName: "Thabo M.",
    location: "Limpopo, South Africa",
    region: "Limpopo",
    cropType: "Maize",
    landHectares: 5,
    fundingGoal: 2.5,
    totalRaised: 1.8,
    milestoneIndex: 3,
    status: "Funded" as const,
    profitSplitBps: 6000,
    seasonStart: "2026-01-15",
    seasonEnd: "2026-07-30",
    riskTier: "Low" as const,
    investors: 8,
    lat: -23.9,
    lng: 29.4,
    lastUpdate: "Vegetative Growth verified 3 days ago",
    description: "Five hectares of prime maize farmland in the fertile valleys of Limpopo. Drip irrigation system installed. Third season farming this plot.",
    collateralVerified: true,
    collateralType: "Land Rights Deed" as const,
    invoiceUploaded: true,
  },
  {
    id: "farm-2",
    farmerName: "Nomsa K.",
    location: "KwaZulu-Natal, South Africa",
    region: "KwaZulu-Natal",
    cropType: "Maize",
    landHectares: 3,
    fundingGoal: 1.8,
    totalRaised: 0.6,
    milestoneIndex: 1,
    status: "Active" as const,
    profitSplitBps: 5500,
    seasonStart: "2026-02-01",
    seasonEnd: "2026-08-15",
    riskTier: "Medium" as const,
    investors: 3,
    lat: -29.6,
    lng: 30.3,
    lastUpdate: "Planting verified 1 week ago",
    description: "Three hectares along the Tugela River basin. Good soil quality with natural water access. Second season with investor funding.",
    collateralVerified: true,
    collateralType: "Future Harvest Guarantee" as const,
    invoiceUploaded: true,
  },
  {
    id: "farm-3",
    farmerName: "Sipho D.",
    location: "Mpumalanga, South Africa",
    region: "Mpumalanga",
    cropType: "Maize",
    landHectares: 8,
    fundingGoal: 4.2,
    totalRaised: 4.2,
    milestoneIndex: 5,
    status: "Funded" as const,
    profitSplitBps: 6500,
    seasonStart: "2025-11-01",
    seasonEnd: "2026-05-30",
    riskTier: "Low" as const,
    investors: 15,
    lat: -25.4,
    lng: 30.9,
    lastUpdate: "Harvest Complete - awaiting final disbursement",
    description: "Eight hectares of established farmland. Center pivot irrigation. Five years of consistent yields. Highest-rated farm on the platform.",
    collateralVerified: true,
    collateralType: "Tractor/Equipment Lien" as const,
    invoiceUploaded: true,
  },
  {
    id: "farm-4",
    farmerName: "Lindiwe N.",
    location: "Free State, South Africa",
    region: "Free State",
    cropType: "Maize",
    landHectares: 4,
    fundingGoal: 2.0,
    totalRaised: 0.0,
    milestoneIndex: 0,
    status: "Pending Documents" as const,
    profitSplitBps: 5000,
    seasonStart: "2026-03-01",
    seasonEnd: "2026-09-15",
    riskTier: "Medium" as const,
    investors: 0,
    lat: -29.1,
    lng: 26.2,
    lastUpdate: "Campaign just launched - awaiting collateral & invoice",
    description: "Four hectares of dryland maize farming in the Free State breadbasket. Well-established rotation system. Looking for first season of blockchain-verified funding.",
    collateralVerified: false,
    collateralType: null,
    invoiceUploaded: false,
  },
];

export const getLoadingMessage = () =>
  LOADING_MESSAGES[Math.floor(Math.random() * LOADING_MESSAGES.length)];